### ISSUE TITLE
sass-loader error when deploying to Heroku

### ISSUE THREAD

**Issue by maebeale** [maebeale/mutual-aid#304]
`ModuleNotFoundError: Module not found: Error: Can't resolve 'sass-loader'`

thank you for guidance, @csexton!!!
https://www.codeography.com/2019/08/02/rails-6-on-heroku.html

https://www.codeography.com/2019/08/22/rails-6-on-heroku-revisited.html

**Comment by maebeale** [comment]
```
➜  git push heroku master
Enumerating objects: 4288, done.
Counting objects: 100% (4171/4171), done.
Delta compression using up to 4 threads
Compressing objects: 100% (2643/2643), done.
Writing objects: 100% (4003/4003), 579.93 KiB | 7.43 MiB/s, done.
Total 4003 (delta 2801), reused 2004 (delta 1311)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Installing bundler 2.0.2
remote: -----> Removing BUNDLED WITH version in the Gemfile.lock
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.7.0
remote: -----> Installing dependencies using bundler 2.0.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        [DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
remote:        [DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
remote:        [DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development:test'`, and stop using this flag
remote:        [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
remote:        Fetching gem metadata from https://rubygems.org/............
remote:        Fetching rake 13.0.1
remote:        Installing rake 13.0.1
remote:        Fetching concurrent-ruby 1.1.6
remote:        Fetching minitest 5.14.0
remote:        Fetching thread_safe 0.3.6
remote:        Installing minitest 5.14.0
remote:        Installing thread_safe 0.3.6
remote:        Installing concurrent-ruby 1.1.6
remote:        Fetching zeitwerk 2.3.0
remote:        Installing zeitwerk 2.3.0
remote:        Fetching builder 3.2.4
remote:        Fetching erubi 1.9.0
remote:        Installing builder 3.2.4
remote:        Installing erubi 1.9.0
remote:        Fetching mini_portile2 2.4.0
remote:        Fetching crass 1.0.6
remote:        Installing mini_portile2 2.4.0
remote:        Installing crass 1.0.6
remote:        Fetching rack 2.2.2
remote:        Fetching nio4r 2.5.2
remote:        Fetching websocket-extensions 0.1.4
remote:        Installing nio4r 2.5.2 with native extensions
remote:        Installing rack 2.2.2
remote:        Installing websocket-extensions 0.1.4
remote:        Fetching mimemagic 0.3.4
remote:        Fetching mini_mime 1.0.2
remote:        Installing mini_mime 1.0.2
remote:        Installing mimemagic 0.3.4
remote:        Fetching bcrypt 3.1.13
remote:        Installing bcrypt 3.1.13 with native extensions
remote:        Fetching blueprinter 0.23.4
remote:        Installing blueprinter 0.23.4
remote:        Fetching msgpack 1.3.3
remote:        Installing msgpack 1.3.3 with native extensions
remote:        Using bundler 2.1.2
remote:        Fetching declarative 0.0.10
remote:        Installing declarative 0.0.10
remote:        Fetching declarative-option 0.1.0
remote:        Installing declarative-option 0.1.0
remote:        Fetching orm_adapter 0.5.0
remote:        Installing orm_adapter 0.5.0
remote:        Fetching method_source 1.0.0
remote:        Installing method_source 1.0.0
remote:        Fetching thor 1.0.1
remote:        Installing thor 1.0.1
remote:        Fetching uber 0.1.0
remote:        Installing uber 0.1.0
remote:        Fetching dotenv 2.7.5
remote:        Installing dotenv 2.7.5
remote:        Fetching ffi 1.12.2
remote:        Installing ffi 1.12.2 with native extensions
remote:        Fetching pg 1.2.3
remote:        Installing pg 1.2.3 with native extensions
remote:        Fetching ruby_http_client 3.5.0
remote:        Installing ruby_http_client 3.5.0
remote:        Fetching tilt 2.0.10
remote:        Installing tilt 2.0.10
remote:        Fetching tzinfo 1.2.6
remote:        Installing tzinfo 1.2.6
remote:        Fetching i18n 1.8.2
remote:        Installing i18n 1.8.2
remote:        Fetching nokogiri 1.10.9
remote:        Installing nokogiri 1.10.9 with native extensions
remote:        Fetching websocket-driver 0.7.1
remote:        Installing websocket-driver 0.7.1 with native extensions
remote:        Fetching rack-test 1.1.0
remote:        Installing rack-test 1.1.0
remote:        Fetching warden 1.2.8
remote:        Installing warden 1.2.8
remote:        Fetching request_store 1.5.0
remote:        Installing request_store 1.5.0
remote:        Fetching rack-proxy 0.6.5
remote:        Installing rack-proxy 0.6.5
remote:        Fetching sprockets 4.0.0
remote:        Installing sprockets 4.0.0
remote:        Fetching mail 2.7.1
remote:        Installing mail 2.7.1
remote:        Fetching marcel 0.3.3
remote:        Installing marcel 0.3.3
remote:        Fetching puma 4.3.3
remote:        Installing puma 4.3.3 with native extensions
remote:        Fetching declarative-builder 0.1.0
remote:        Installing declarative-builder 0.1.0
remote:        Fetching representable 3.0.4
remote:        Installing representable 3.0.4
remote:        Fetching bootsnap 1.4.6
remote:        Installing bootsnap 1.4.6 with native extensions
remote:        Fetching sendgrid-ruby 6.2.0
remote:        Installing sendgrid-ruby 6.2.0
remote:        Fetching activesupport 6.0.2.2
remote:        Installing activesupport 6.0.2.2
remote:        Fetching sassc 2.2.1
remote:        Installing sassc 2.2.1 with native extensions
remote:        Fetching mobility 0.8.10
remote:        Installing mobility 0.8.10
remote:        Fetching loofah 2.4.0
remote:        Installing loofah 2.4.0
remote:        Fetching disposable 0.4.7
remote:        Installing disposable 0.4.7
remote:        Fetching rails-dom-testing 2.0.3
remote:        Installing rails-dom-testing 2.0.3
remote:        Fetching globalid 0.4.2
remote:        Installing globalid 0.4.2
remote:        Fetching activemodel 6.0.2.2
remote:        Installing activemodel 6.0.2.2
remote:        Fetching jbuilder 2.10.0
remote:        Installing jbuilder 2.10.0
remote:        Fetching rails-html-sanitizer 1.3.0
remote:        Installing rails-html-sanitizer 1.3.0
remote:        Fetching reform 2.2.4
remote:        Fetching activejob 6.0.2.2
remote:        Installing reform 2.2.4
remote:        Installing activejob 6.0.2.2
remote:        Fetching activerecord 6.0.2.2
remote:        Fetching active_interaction 3.8.2
remote:        Installing active_interaction 3.8.2
remote:        Installing activerecord 6.0.2.2
remote:        Fetching actionview 6.0.2.2
remote:        Installing actionview 6.0.2.2
remote:        Fetching reform-rails 0.1.7
remote:        Installing reform-rails 0.1.7
remote:        Fetching actionpack 6.0.2.2
remote:        Fetching acts-as-taggable-on 6.5.0
remote:        Installing acts-as-taggable-on 6.5.0
remote:        Installing actionpack 6.0.2.2
remote:        Fetching actioncable 6.0.2.2
remote:        Fetching activestorage 6.0.2.2
remote:        Installing actioncable 6.0.2.2
remote:        Installing activestorage 6.0.2.2
remote:        Fetching actionmailer 6.0.2.2
remote:        Fetching railties 6.0.2.2
remote:        Installing actionmailer 6.0.2.2
remote:        Installing railties 6.0.2.2
remote:        Fetching sprockets-rails 3.2.1
remote:        Installing sprockets-rails 3.2.1
remote:        Fetching simple_form 5.0.2
remote:        Installing simple_form 5.0.2
remote:        Fetching actionmailbox 6.0.2.2
remote:        Installing actionmailbox 6.0.2.2
remote:        Fetching actiontext 6.0.2.2
remote:        Installing actiontext 6.0.2.2
remote:        Fetching responders 3.0.0
remote:        Fetching dotenv-rails 2.7.5
remote:        Installing responders 3.0.0
remote:        Installing dotenv-rails 2.7.5
remote:        Fetching webpacker 4.2.2
remote:        Fetching rails 6.0.2.2
remote:        Installing rails 6.0.2.2
remote:        Installing webpacker 4.2.2
remote:        Fetching devise 4.7.1
remote:        Installing devise 4.7.1
remote:        Fetching sassc-rails 2.1.2
remote:        Installing sassc-rails 2.1.2
remote:        Fetching sass-rails 6.0.0
remote:        Installing sass-rails 6.0.0
remote:        Bundle complete! 31 Gemfile dependencies, 78 gems now installed.
remote:        Gems in the groups development and test were not installed.
remote:        Bundled gems are installed into `./vendor/bundle`
remote:        Post-install message from i18n:
remote:
remote:        HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
remote:        But that may break your application.
remote:
remote:        If you are upgrading your Rails application from an older version of Rails:
remote:
remote:        Please check your Rails app for 'config.i18n.fallbacks = true'.
remote:        If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
remote:        'config.i18n.fallbacks = [I18n.default_locale]'.
remote:        If not, fallbacks will be broken in your app by I18n 1.1.x.
remote:
remote:        If you are starting a NEW Rails application, you can ignore this notice.
remote:
remote:        For more info see:
remote:        https://github.com/svenfuchs/i18n/releases/tag/v1.1.0
remote:
remote:        Post-install message from acts-as-taggable-on:
remote:        When upgrading
remote:
remote:        Re-run the migrations generator
remote:
remote:            rake acts_as_taggable_on_engine:install:migrations
remote:
remote:        This will create any new migrations and skip existing ones
remote:        Version 3.5.0 has a migration for mysql adapter
remote:        Removing bundler (2.0.2)
remote:        Bundle completed (183.87s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v10.15.3-linux-x64
remote: -----> Installing yarn-v1.16.0
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        /tmp/build_4938ac0804a9269eb65ef583cc441c02/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type.rb:27: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
remote:        /tmp/build_4938ac0804a9269eb65ef583cc441c02/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.2/lib/active_record/type/adapter_specific_registry.rb:9: warning: The called method `add_modifier' is defined here
remote:        /tmp/build_4938ac0804a9269eb65ef583cc441c02/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/stack.rb:37: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
remote:        /tmp/build_4938ac0804a9269eb65ef583cc441c02/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/static.rb:110: warning: The called method `initialize' is defined here
remote:        yarn install v1.16.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.12: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 34.04s.
remote:        yarn install v1.16.0
remote:        [1/4] Resolving packages...
remote:        [2/4] Fetching packages...
remote:        info fsevents@1.2.12: The platform "linux" is incompatible with this module.
remote:        info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
remote:        [3/4] Linking dependencies...
remote:        warning " > babel-loader@8.1.0" has unmet peer dependency "@babel/core@^7.0.0".
remote:        [4/4] Building fresh packages...
remote:        Done in 6.63s.
remote:        I, [2020-05-18T12:28:44.951053 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/manifest-cadda289ef9c70eaa0879a36e6263cb33f7523a16b3ef862e0b8609cdc2bdab1.js
remote:        I, [2020-05-18T12:28:44.951402 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/manifest-cadda289ef9c70eaa0879a36e6263cb33f7523a16b3ef862e0b8609cdc2bdab1.js.gz
remote:        I, [2020-05-18T12:28:44.952338 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/logo-8145f83f38f1c05eadf485159081c3a200512f4727c52c6a3361baa2c6c74969.png
remote:        I, [2020-05-18T12:28:44.952809 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/missing-3b808c852a3162487054186a9e456103f3284799ac8eee10220ec228d3df2e54.png
remote:        I, [2020-05-18T12:28:44.953219 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/application-b07356224726c2a37203bd6aea7e9d75489d8b8573bd38cedf8dba8e5e357f7f.css
remote:        I, [2020-05-18T12:28:44.953410 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/application-b07356224726c2a37203bd6aea7e9d75489d8b8573bd38cedf8dba8e5e357f7f.css.gz
remote:        I, [2020-05-18T12:28:44.953727 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/bulma_and_buefy-43934ca59725cb1e12e4acdb2d5608b9a179eab15033d23485b71a4f526fec8a.css
remote:        I, [2020-05-18T12:28:44.953942 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/bulma_and_buefy-43934ca59725cb1e12e4acdb2d5608b9a179eab15033d23485b71a4f526fec8a.css.gz
remote:        I, [2020-05-18T12:28:44.954167 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/bulma_simple_form_customization-fd30279bf9436f7935e0c8f4c6af665ff315d3bb88ba7182ce151caa477d4409.css
remote:        I, [2020-05-18T12:28:44.954460 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/bulma_simple_form_customization-fd30279bf9436f7935e0c8f4c6af665ff315d3bb88ba7182ce151caa477d4409.css.gz
remote:        I, [2020-05-18T12:28:44.954700 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/custom_spacing_helpers-7bb72b11dc9dc97f891b5500bcc736b4cb2296b23364a56e9f8f2b61c79f4eb8.css
remote:        I, [2020-05-18T12:28:44.954895 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/custom_spacing_helpers-7bb72b11dc9dc97f891b5500bcc736b4cb2296b23364a56e9f8f2b61c79f4eb8.css.gz
remote:        I, [2020-05-18T12:28:44.955175 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/font_awesome-f6f886f5b5bf6c2f41d910f3e731cb0b8d17b98fe1f8ef46caebe50f6c2aee83.css
remote:        I, [2020-05-18T12:28:44.955336 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/font_awesome-f6f886f5b5bf6c2f41d910f3e731cb0b8d17b98fe1f8ef46caebe50f6c2aee83.css.gz
remote:        I, [2020-05-18T12:28:44.955561 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/listings-83bc7609d803a272d311e94279143abbc8962dccf568a4d826b3012717f8343f.css
remote:        I, [2020-05-18T12:28:44.956957 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/listings-83bc7609d803a272d311e94279143abbc8962dccf568a4d826b3012717f8343f.css.gz
remote:        I, [2020-05-18T12:28:44.957383 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/variables-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.css
remote:        I, [2020-05-18T12:28:44.957566 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/variables-d0ff5974b6aa52cf562bea5921840c032a860a91a3512f7fe8f768f6bbe005f6.css.gz
remote:        I, [2020-05-18T12:28:44.958022 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/yearbook-0bde9bed7b2fd171b73d321b65d13348c78465da2e700ced84344f4017ac09e7.css
remote:        I, [2020-05-18T12:28:44.958270 #1719]  INFO -- : Writing /tmp/build_4938ac0804a9269eb65ef583cc441c02/public/assets/yearbook-0bde9bed7b2fd171b73d321b65d13348c78465da2e700ced84344f4017ac09e7.css.gz
remote:        Compiling...
remote:        Compilation failed:
remote:        ModuleNotFoundError: Module not found: Error: Can't resolve 'sass-loader' in '/tmp/build_4938ac0804a9269eb65ef583cc441c02'
remote:            at factory.create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/webpack/lib/Compilation.js:925:10)
remote:            at factory (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
remote:            at resolver (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
remote:            at asyncLib.parallel (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/webpack/lib/NormalModuleFactory.js:337:24)
remote:            at /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/neo-async/async.js:2830:7
remote:            at /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/neo-async/async.js:6877:13
remote:            at /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/neo-async/async.js:2830:7
remote:            at done (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/neo-async/async.js:2925:13)
remote:            at resolver.resolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/webpack/lib/NormalModuleFactory.js:449:23)
remote:            at doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at resolver.doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at resolver.doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at resolver.doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at args (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/forEachBail.js:30:14)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at resolver.doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn0 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
remote:            at resolver.doResolve (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
remote:            at hook.callAsync (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
remote:            at _fn1 (eval at create (/tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
remote:        resolve 'sass-loader' in '/tmp/build_4938ac0804a9269eb65ef583cc441c02'
remote:          Parsed request is a module
remote:          using description file: /tmp/build_4938ac0804a9269eb65ef583cc441c02/package.json (relative path: .)
remote:            resolve as module
remote:              /tmp/node_modules doesn't exist or is not a directory
remote:              /node_modules doesn't exist or is not a directory
remote:              looking for modules in /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules
remote:                using description file: /tmp/build_4938ac0804a9269eb65ef583cc441c02/package.json (relative path: ./node_modules)
remote:                  using description file: /tmp/build_4938ac0804a9269eb65ef583cc441c02/package.json (relative path: ./node_modules/sass-loader)
remote:                    no extension
remote:                      /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/sass-loader doesn't exist
remote:                    .js
remote:                      /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/sass-loader.js doesn't exist
remote:                    .json
remote:                      /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/sass-loader.json doesn't exist
remote:                    as directory
remote:                      /tmp/build_4938ac0804a9269eb65ef583cc441c02/node_modules/sass-loader doesn't exist
remote:
remote:
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !	Push rejected to [YOURAPPNAME].
remote:
To https://git.heroku.com/[YOURAPPNAME].git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/[YOURAPPNAME]'
```

**Comment by csexton** [comment]
Yay! Glad it was helpful 😀

**Comment by maebeale** [comment]
We're still not out of the woods, @csexton, but this confirmed all the efforts we've made this far -- and gave us some new ideas too. THANKS!

**Comment by csexton** [comment]
Is this deploy running off master? Looking at `package.json` I see you still have ` "sass-loader"` under `devDependencies`. You could try moving that to `dependencies` and see if the default build pack will work with that.

https://github.com/maebeale/mutual-aid/blob/master/package.json#L31
